[package]
name = "gigagen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
glob = "0.3"
cbindgen = "0.26"
csbindgen = "1.8.0"

[dependencies]
glam = "0.24"
rayon = "1.8"
noise = "0.8"
num_cpus = "1.0"
